"""empty message

Revision ID: ccdcb72ef589
Revises: 95cc814a1fde
Create Date: 2023-12-16 02:42:18.530447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccdcb72ef589'
down_revision = '95cc814a1fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('subject')
    op.drop_table('favorites_subject')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('rol')
        batch_op.drop_column('public_id_avatar')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('public_id_avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rol', postgresql.ENUM('admin', 'general', 'instructor', name='userrol'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_active')

    op.create_table('favorites_subject',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='favorites_subject_subject_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_subject_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_subject_pkey')
    )
    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_banner', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='subject_pkey')
    )
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['user.id'], name='favorites_instructor_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name='favorites_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    # ### end Alembic commands ###
